config/routes.rb
FulbitoFacil::Application.routes.draw do    

  resources :alquilers

  resources :tarifas

  resources :horario_atencions

  resources :dia_semanas

  resources :canchas

  resources :canchita
  resources :publicities

  resources :comments

  resources :ubications

  devise_for :usercustomers, :customers ,:owners 
  

  devise_scope :customer do
      match "inicioSesionJugador" => "devise/sessions#new"
      
     
  end
  devise_scope :owner do
      match "inicioSesionOwner" => "devise/sessions#new"
  
  end

  resources :additional_services

  resources :service_types

  resources :rates

  resources :sportsfields

  match "registro" => "vistasGenerales#registro"
  match "registroDueno" => "owners#new"
  match "registroJugador" => "customers#new"
  match "buscarCanchas" => "canchas#alquilar"
  match "reservarCanchas" => "alquilers#new"
  match "reservaActual" => "customers#new"
  match "panelJugador/:id" => "customers#show", :as =>'panelJugador'
  match "panelOwner/:id" => "owners#show", :as =>'panelOwner'
  match "localesOwner/:id" => "locals#index", :as =>'localesOwner'
  match "panel" => "vistasGenerales#panel"
  match "reservas" => "customers#new"
  match "canchitasLocal/:id" => "canchas#index", :as =>'canchitasLocal'
  match "tarifasCanchita/:id" => "tarifas#index", :as =>'tarifasCanchita'
  match "horarioCanchita/:id" => "horarioAtencions#index", :as =>'horarioCanchita'
  match "reservasJugador/:id" => "alquilers#alqJugador", :as =>'reservasJugador'
  

  get "sign_up" => "customers#new", :as => "sign_up"

root :to => "vistasGenerales#index"

  

  resources :customers

  resources :locals

  resources :districts

  resources :owners

  resources :identity_card_types

  resources :generes

  resources :identity_card_types

  resources :id_types

end

app/models/owner.rb
class Owner < ActiveRecord::Base
  belongs_to :genere
  belongs_to :local
  belongs_to :identity_card_type

  devise :database_authenticatable, :timeoutable, :timeoutable
  
  #validates_presence_of :name, :lastname, :genere_id, :identity_card_type_id, 		 :number_identity_card, :email, :password, :birthday
  #validates_uniqueness_of :email
  #validates :number_identity_card, :numericality => { :only_integer => true }
  #validate :validation_password
  #validate :validation_email
  	
#def validation_password		
#errors.add(:password_confirmation, "Las contrasenas introducidas no coinciden. Vuelve a intentarlo.") if(password_confirmation!=password)				end
#end
#def validation_email		
#errors.add(:email_confirmation, "Las direcciones de correo electronico introducidas no coinciden. Vuelve a intentarlo.") if(password_confirmation!=password)			
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  # GET /owners
  # GET /owners.json
  
  
  def index
    @owners = Owner.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @owners }
    end
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
    @owner = Owner.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @owner }
    end
  end

  # GET /owners/new
  # GET /owners/new.json
  def new
    @owner = Owner.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @owner }
    end
  end

  # GET /owners/1/edit
  def edit
    @owner = Owner.find(params[:id])
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(params[:owner])

    respond_to do |format|
      if @owner.save
        format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
        format.json { render json: @owner, status: :created, location: @owner }
      else
        format.html { render action: "new" }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /owners/1
  # PUT /owners/1.json
  def update
    @owner = Owner.find(params[:id])

    respond_to do |format|
      if @owner.update_attributes(params[:owner])
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner = Owner.find(params[:id])
    @owner.destroy

    respond_to do |format|
      format.html { redirect_to owners_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/owners/_form.html.erb
<section id="contenedorBasico">
<%= simple_form_for(@owner) do |f| %>
 <% if @owner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@owner.errors.count, "error") %> prohibited this owner from being saved:</h2>

	       <ul>
      <% if(@owner).errors.any? %>
	<% @owner.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
	<% end %>
      <% end %>
      </ul>
    </div>
  <% end %>


    <%= f.input :name,:label=> "Nombres : "  %>
    <%= f.input :lastname,:label=>"Apellidos : " %>
    <%= f.association:genere, :label=> "Genero : ", :as => :radio %>
    <%= f.association :identity_card_type, :label=> "Tipo de Documento : " %>
    <%= f.input :number_identity_card, :label=> "Numero de Documento : " %>
    <%= f.input :email, :label=> "Correo Electronico : "%>
    <%= f.input :email_confirmation, :label=> "Confirmar Correo Electronico : "%>
    <%= f.input :password, :label=> "Password : " %>
    <%= f.input :password_confirmation, :label=> "Confirmar Password : " %>
    <%= f.input :birthday, :label => "Fecha de Nacimiento : "  %>
    <%= f.submit 'Aceptar'  %>
<% end %>
</section>

app/views/owners/edit.html.erb
<h1>Editing owner</h1>

<%= render 'form' %>

<%= link_to 'Show', @owner %> |
<%= link_to 'Back', owners_path %>

app/views/owners/index.html.erb
<section id="contenedorBasico">
<h1>Lista de Duenos de Canchitas de Fulbito</h1>

<table border="1">
  <tr>
    <th>Nombres</th>
    <th>Apellidos</th>
    <th>Genero</th>
    <th>Tipo de Documento de Identidad</th>
    <th>Numero de Documento de Identidad</th>
    <th>Correo Electronico</th>
    <th>Password</th>
    <th>Fecha de Nacimiento</th>
  </tr>

<% @owners.each do |owner| %>
  <tr>
    <td><%= owner.name %></td>
    <td><%= owner.lastname %></td>
    <td><%= owner.genere.name.to_s %></td>
    <td><%= owner.identity_card_type.name.to_s %></td>
    <td><%= owner.number_identity_card %></td>
    <td><%= owner.email %></td>
    <td><%= owner.password %></td>
    <td><%= owner.birthday %></td>
    <td><%= link_to 'Show', owner %></td>
    <td><%= link_to 'Edit', edit_owner_path(owner) %></td>
    <td><%= link_to 'Destroy', owner, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nuevo Dueno de Canchitas de Fulbito', new_owner_path %>
</section>

app/views/owners/new.html.erb
<h1>Create una cuenta de dueño de cancha</h1>

<%= render 'form' %>

app/views/owners/show.html.erb
<section id="contenedorBasico">
<h1>Panel de control Propietario de Canchitas</h1>
<section id="datosGeneralesPanel">
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @owner.name %>
</p>

<p>
  <b>Lastname:</b>
  <%= @owner.lastname %>
</p>

<p>
  <b>Genere:</b>
  <%= @owner.genere.name.to_s %>
</p>

<p>
  <b>Identity card type:</b>
  <%= @owner.identity_card_type.name.to_s %>
</p>

<p>
  <b>Number identity card:</b>
  <%= @owner.number_identity_card %>
</p>

<p>
  <b>Email:</b>
  <%= @owner.email %>
</p>

<p>
  <b>Password:</b>
  <%= @owner.password %>
</p>

<p>
  <b>Birthday:</b>
  <%= @owner.birthday %>
</p>


<%= link_to 'Edit', edit_owner_path(@owner) %> |
</section>
  <section id="datosOpcionesPanel">
    <div id="buttons">
                        <div id="button_left" align="center">
                            <%= link_to "Locales", localesOwner_path(@owner) %>
                        </div>
                        <div id="button_left" align="center">
                             <%= link_to "Canchitas", sportsfields_path %>
                        </div>
                        <div id="button_left" align="center">
                            <%= link_to "Reservas", locals_path %>
                        </div>
                        
                        <div class="clear"></div>
                    </div>

  </section>