config/routes.rb
FulbitoFacil::Application.routes.draw do    

  resources :alquilers

  resources :tarifas

  resources :horario_atencions

  resources :dia_semanas

  resources :canchas

  resources :canchita
  resources :publicities

  resources :comments

  resources :ubications

  devise_for :usercustomers, :customers ,:owners 
  

  devise_scope :customer do
      match "inicioSesionJugador" => "devise/sessions#new"
      
     
  end
  devise_scope :owner do
      match "inicioSesionOwner" => "devise/sessions#new"
  
  end

  resources :additional_services

  resources :service_types

  resources :rates

  resources :sportsfields

  match "registro" => "vistasGenerales#registro"
  match "registroDueno" => "owners#new"
  match "registroJugador" => "customers#new"
  match "buscarCanchas" => "canchas#alquilar"
  match "reservarCanchas" => "alquilers#new"
  match "reservaActual" => "customers#new"
  match "panelJugador/:id" => "customers#show", :as =>'panelJugador'
  match "panelOwner/:id" => "owners#show", :as =>'panelOwner'
  match "localesOwner/:id" => "locals#index", :as =>'localesOwner'
  match "panel" => "vistasGenerales#panel"
  match "reservas" => "customers#new"
  match "canchitasLocal/:id" => "canchas#index", :as =>'canchitasLocal'
  match "tarifasCanchita/:id" => "tarifas#index", :as =>'tarifasCanchita'
  match "horarioCanchita/:id" => "horarioAtencions#index", :as =>'horarioCanchita'
  match "reservasJugador/:id" => "alquilers#alqJugador", :as =>'reservasJugador'
  

  get "sign_up" => "customers#new", :as => "sign_up"

root :to => "vistasGenerales#index"

  

  resources :customers

  resources :locals

  resources :districts

  resources :owners

  resources :identity_card_types

  resources :generes

  resources :identity_card_types

  resources :id_types

end

app/models/dia_semana.rb
class DiaSemana < ActiveRecord::Base
end

app/controllers/dia_semanas_controller.rb
class DiaSemanasController < ApplicationController
  # GET /dia_semanas
  # GET /dia_semanas.json
  def index
    @dia_semanas = DiaSemana.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dia_semanas }
    end
  end

  # GET /dia_semanas/1
  # GET /dia_semanas/1.json
  def show
    @dia_semana = DiaSemana.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dia_semana }
    end
  end

  # GET /dia_semanas/new
  # GET /dia_semanas/new.json
  def new
    @dia_semana = DiaSemana.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dia_semana }
    end
  end

  # GET /dia_semanas/1/edit
  def edit
    @dia_semana = DiaSemana.find(params[:id])
  end

  # POST /dia_semanas
  # POST /dia_semanas.json
  def create
    @dia_semana = DiaSemana.new(params[:dia_semana])

    respond_to do |format|
      if @dia_semana.save
        format.html { redirect_to @dia_semana, notice: 'Dia semana was successfully created.' }
        format.json { render json: @dia_semana, status: :created, location: @dia_semana }
      else
        format.html { render action: "new" }
        format.json { render json: @dia_semana.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dia_semanas/1
  # PUT /dia_semanas/1.json
  def update
    @dia_semana = DiaSemana.find(params[:id])

    respond_to do |format|
      if @dia_semana.update_attributes(params[:dia_semana])
        format.html { redirect_to @dia_semana, notice: 'Dia semana was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dia_semana.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dia_semanas/1
  # DELETE /dia_semanas/1.json
  def destroy
    @dia_semana = DiaSemana.find(params[:id])
    @dia_semana.destroy

    respond_to do |format|
      format.html { redirect_to dia_semanas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/dia_semanas_helper.rb
module DiaSemanasHelper
end

app/views/dia_semanas/_form.html.erb
<%= simple_form_for(@dia_semana) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">

    <%= f.input :name %>

  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/dia_semanas/edit.html.erb
<h1>Editing dia_semana</h1>

<%= render 'form' %>

<%= link_to 'Show', @dia_semana %> |
<%= link_to 'Back', dia_semanas_path %>

app/views/dia_semanas/index.html.erb
<h1>Listing dia_semanas</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dia_semanas.each do |dia_semana| %>
  <tr>
    <td><%= dia_semana.name %></td>
    <td><%= link_to 'Show', dia_semana %></td>
    <td><%= link_to 'Edit', edit_dia_semana_path(dia_semana) %></td>
    <td><%= link_to 'Destroy', dia_semana, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dia semana', new_dia_semana_path %>

app/views/dia_semanas/new.html.erb
<h1>New dia_semana</h1>

<%= render 'form' %>

<%= link_to 'Back', dia_semanas_path %>

app/views/dia_semanas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @dia_semana.name %>
</p>


<%= link_to 'Edit', edit_dia_semana_path(@dia_semana) %> |
<%= link_to 'Back', dia_semanas_path %>