config/routes.rb
FulbitoFacil::Application.routes.draw do    

  resources :alquilers

  resources :tarifas

  resources :horario_atencions

  resources :dia_semanas

  resources :canchas

  resources :canchita
  resources :publicities

  resources :comments

  resources :ubications

  devise_for :usercustomers, :customers ,:owners 
  

  devise_scope :customer do
      match "inicioSesionJugador" => "devise/sessions#new"
      
     
  end
  devise_scope :owner do
      match "inicioSesionOwner" => "devise/sessions#new"
  
  end

  resources :additional_services

  resources :service_types

  resources :rates

  resources :sportsfields

  match "registro" => "vistasGenerales#registro"
  match "registroDueno" => "owners#new"
  match "registroJugador" => "customers#new"
  match "buscarCanchas" => "canchas#alquilar"
  match "reservarCanchas" => "alquilers#new"
  match "reservaActual" => "customers#new"
  match "panelJugador/:id" => "customers#show", :as =>'panelJugador'
  match "panelOwner/:id" => "owners#show", :as =>'panelOwner'
  match "localesOwner/:id" => "locals#index", :as =>'localesOwner'
  match "panel" => "vistasGenerales#panel"
  match "reservas" => "customers#new"
  match "canchitasLocal/:id" => "canchas#index", :as =>'canchitasLocal'
  match "tarifasCanchita/:id" => "tarifas#index", :as =>'tarifasCanchita'
  match "horarioCanchita/:id" => "horarioAtencions#index", :as =>'horarioCanchita'
  match "reservasJugador/:id" => "alquilers#alqJugador", :as =>'reservasJugador'
  

  get "sign_up" => "customers#new", :as => "sign_up"

root :to => "vistasGenerales#index"

  

  resources :customers

  resources :locals

  resources :districts

  resources :owners

  resources :identity_card_types

  resources :generes

  resources :identity_card_types

  resources :id_types

end

app/models/alquiler.rb
class Alquiler < ActiveRecord::Base
  belongs_to :cancha
  belongs_to :customer
  belongs_to :dia_semana
end

app/controllers/alquilers_controller.rb
class AlquilersController < ApplicationController
  # GET /alquilers
  # GET /alquilers.json
  def index
    @alquilers = Alquiler.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @alquilers }
    end
  end
  def alqPropietario

    @alquilers = Alquiler.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @alquilers }
    end
  end
  def alqJugador
    @search = Alquiler.where(:customer_id => params[:id])     
    @alquilers= @search.all    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @alquilers }
    end
  end
  # GET /alquilers/1
  # GET /alquilers/1.json
  def show
    @alquiler = Alquiler.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @alquiler }
    end
  end

  # GET /alquilers/new
  # GET /alquilers/new.json
  def new
    @alquiler = Alquiler.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @alquiler }
    end
  end

  # GET /alquilers/1/edit
  def edit
    @alquiler = Alquiler.find(params[:id])
  end

  # POST /alquilers
  # POST /alquilers.json
  def create
    @alquiler = Alquiler.new(params[:alquiler])

    respond_to do |format|
      if @alquiler.save
        format.html { redirect_to @alquiler, notice: 'Alquiler was successfully created.' }
        format.json { render json: @alquiler, status: :created, location: @alquiler }
      else
        format.html { render action: "new" }
        format.json { render json: @alquiler.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /alquilers/1
  # PUT /alquilers/1.json
  def update
    @alquiler = Alquiler.find(params[:id])

    respond_to do |format|
      if @alquiler.update_attributes(params[:alquiler])
        format.html { redirect_to @alquiler, notice: 'Alquiler was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @alquiler.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alquilers/1
  # DELETE /alquilers/1.json
  def destroy
    @alquiler = Alquiler.find(params[:id])
    @alquiler.destroy

    respond_to do |format|
      format.html { redirect_to alquilers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/alquilers_helper.rb
module AlquilersHelper
end

app/views/alquilers/_form.html.erb
<%= simple_form_for(@alquiler) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">

    <%= f.association :cancha %>

    <%= f.association :customer %>

    <%= f.association :dia_semana %>

    <%= f.input :star_time %>

    <%= f.input :end_time %>

  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/alquilers/alqJugador.html.erb
<section id="contenedorBasico">
<h1>Historial de Alquileres</h1>

<table>
  <tr>
    <th>Cancha</th>
    <th>Dia semana</th>
    <th>Star time</th>
    <th>End time</th>
    <th></th>
    <th></th>
    
  </tr>

<% @alquilers.each do |alquiler| %>
  <tr>
    <td><%= alquiler.cancha.name %></td>
    <td><%= alquiler.dia_semana.name %></td>
    <td><%= alquiler.star_time.strftime("%H:%M") %></td>
    <td><%= alquiler.end_time.strftime("%H:%M") %></td>
    <td><%= link_to 'Detalles', alquiler %></td>
    <td><%= link_to 'Eliminar', alquiler, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Alquiler', new_alquiler_path %>
</section>

app/views/alquilers/edit.html.erb
<h1>Editing alquiler</h1>

<%= render 'form' %>

<%= link_to 'Show', @alquiler %> |
<%= link_to 'Back', alquilers_path %>

app/views/alquilers/index.html.erb
<h1>Lista de alquilers</h1>

<table>
  <tr>
    <th>Cancha</th>
    <th>Customer</th>
    <th>Dia semana</th>
    <th>Star time</th>
    <th>End time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @alquilers.each do |alquiler| %>
  <tr>
    <td><%= alquiler.cancha.name %></td>
    <td><%= alquiler.customer.name %></td>
    <td><%= alquiler.dia_semana.name %></td>
    <td><%= alquiler.star_time.strftime("%H:%M") %></td>
    <td><%= alquiler.end_time.strftime("%H:%M") %></td>
    <td><%= link_to 'Show', alquiler %></td>
    <td><%= link_to 'Edit', edit_alquiler_path(alquiler) %></td>
    <td><%= link_to 'Destroy', alquiler, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Alquiler', new_alquiler_path %>

app/views/alquilers/new.html.erb
<h1>New alquiler</h1>

<%= render 'form' %>

<%= link_to 'Back', alquilers_path %>

app/views/alquilers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cancha:</b>
  <%= @alquiler.cancha %>
</p>

<p>
  <b>Customer:</b>
  <%= @alquiler.customer %>
</p>

<p>
  <b>Dia semana:</b>
  <%= @alquiler.dia_semana %>
</p>

<p>
  <b>Star time:</b>
  <%= @alquiler.star_time %>
</p>

<p>
  <b>End time:</b>
  <%= @alquiler.end_time %>
</p>


<%= link_to 'Edit', edit_alquiler_path(@alquiler) %> |
<%= link_to 'Back', alquilers_path %>