config/routes.rb
FulbitoFacil::Application.routes.draw do    

  resources :alquilers

  resources :tarifas

  resources :horario_atencions

  resources :dia_semanas

  resources :canchas

  resources :canchita
  resources :publicities

  resources :comments

  resources :ubications

  devise_for :usercustomers, :customers ,:owners 
  

  devise_scope :customer do
      match "inicioSesionJugador" => "devise/sessions#new"
      
     
  end
  devise_scope :owner do
      match "inicioSesionOwner" => "devise/sessions#new"
  
  end

  resources :additional_services

  resources :service_types

  resources :rates

  resources :sportsfields

  match "registro" => "vistasGenerales#registro"
  match "registroDueno" => "owners#new"
  match "registroJugador" => "customers#new"
  match "buscarCanchas" => "canchas#alquilar"
  match "reservarCanchas" => "alquilers#new"
  match "reservaActual" => "customers#new"
  match "panelJugador/:id" => "customers#show", :as =>'panelJugador'
  match "panelOwner/:id" => "owners#show", :as =>'panelOwner'
  match "localesOwner/:id" => "locals#index", :as =>'localesOwner'
  match "panel" => "vistasGenerales#panel"
  match "reservas" => "customers#new"
  match "canchitasLocal/:id" => "canchas#index", :as =>'canchitasLocal'
  match "tarifasCanchita/:id" => "tarifas#index", :as =>'tarifasCanchita'
  match "horarioCanchita/:id" => "horarioAtencions#index", :as =>'horarioCanchita'
  match "reservasJugador/:id" => "alquilers#alqJugador", :as =>'reservasJugador'
  

  get "sign_up" => "customers#new", :as => "sign_up"

root :to => "vistasGenerales#index"

  

  resources :customers

  resources :locals

  resources :districts

  resources :owners

  resources :identity_card_types

  resources :generes

  resources :identity_card_types

  resources :id_types

end

app/models/publicity.rb
class Publicity < ActiveRecord::Base
has_attached_file :imagen, :styles => { :small => "150x150>"},
				   :url => "/assets/publicities/:id/:style/:basename.extension",
				   :path => ":rails_root/public//assets/publicities/:id/:style/:basename.extension"

validates_attachment_presence :imagen
validates_attachment_size :imagen, :less_than => 5.megabytes  				   
validates_attachment_content_type :imagen, :content_type => ['image/jpg', 'image/png'] 				   
belongs_to :local
validates_presence_of :name, :local, :feature

  belongs_to :ubications
end

app/controllers/publicities_controller.rb
class PublicitiesController < ApplicationController
  # GET /publicities
  # GET /publicities.json
  def index
  @search = Sportsfield.search(params[:search])
    @publicities = Publicity.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @publicities }
    end
  end

  # GET /publicities/1
  # GET /publicities/1.json
  def show
    @publicity = Publicity.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @publicity }
    end
  end
  


  # GET /publicities/new
  # GET /publicities/new.json
  def new
    @publicity = Publicity.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @publicity }
    end
  end

  # GET /publicities/1/edit
  def edit
    @publicity = Publicity.find(params[:id])
  end

  # POST /publicities
  # POST /publicities.json
  def create
    @publicity = Publicity.new(params[:publicity])

    respond_to do |format|
      if @publicity.save
        format.html { redirect_to @publicity, notice: 'Publicity was successfully created.' }
        format.json { render json: @publicity, status: :created, location: @publicity }
      else
        format.html { render action: "new" }
        format.json { render json: @publicity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /publicities/1
  # PUT /publicities/1.json
  def update
    @publicity = Publicity.find(params[:id])

    respond_to do |format|
      if @publicity.update_attributes(params[:publicity])
        format.html { redirect_to @publicity, notice: 'Publicity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @publicity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publicities/1
  # DELETE /publicities/1.json
  def destroy
    @publicity = Publicity.find(params[:id])
    @publicity.destroy

    respond_to do |format|
      format.html { redirect_to publicities_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/publicities_helper.rb
module PublicitiesHelper
end

app/views/publicities/_form.html.erb
<%= simple_form_for @publicity, :html => { :multipart => true }  do |f| %>
  <%= f.error_notification %>

  
  
  <SCRIPT>
<!--
 function nameDefined(ckie,nme)
{
   var splitValues
   var i
   for (i=0;i<ckie.length;++i)
   {
      splitValues=ckie[i].split("=")
      if (splitValues[0]==nme) return true
   }
   return false
}

function delBlanks(strng)
{
   var result=""
   var i
   var chrn
   for (i=0;i<strng.length;++i) {
      chrn=strng.charAt(i)
      if (chrn!=" ") result += chrn
   }
   return result
}
function getCookieValue(ckie,nme)
{
   var splitValues
   var i
   for(i=0;i<ckie.length;++i) {
      splitValues=ckie[i].split("=")
      if(splitValues[0]==nme) return splitValues[1]
   }
   return ""
}
function insertCounter() {
 readCookie()
 displayCounter()
}
 function displayCounter() {
 document.write('<p>')
 document.write("Hits:")
 if(counter==1) document.write("0")
 else document.write(counter+" times.")
 document.writeln('</p>')
 }
function readCookie() {
 var cookie=document.cookie
 counter=0
 var chkdCookie=delBlanks(cookie)  //are on the client computer
 var nvpair=chkdCookie.split(";")
 if(nameDefined(nvpair,"pageCount"))
 counter=parseInt(getCookieValue(nvpair,"pageCount"))
 ++counter
 var futdate = new Date()
 var expdate = futdate.getTime()
 expdate += 3600000 * 24 *30  //expires in 1 hour
 futdate.setTime(expdate)

 var newCookie="pageCount="+counter
 newCookie += "; expires=" + futdate.toGMTString()
 window.document.cookie=newCookie
}
// -->
</SCRIPT>


 
  <div class="inputs">

    <%= f.input :titulo %>
   <%= f.file_field :contenido %>
   

    <%= f.input :fechaInicio %>

    <%= f.input :fechaFin %>

    <%= f.input :tarifa %>

  
	
<SCRIPT>
<!--
insertCounter()
// -->
</SCRIPT>
<br>	
   <%= f.label :ubications_id %>  
    <%= collection_select("ubications", "ubications_id" , Ubication.all, "id", "name")%>
	
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/publicities/edit.html.erb
<h1>Editing publicity</h1>

<%= render 'form' %>

<%= link_to 'Show', @publicity %> |
<%= link_to 'Back', publicities_path %>

app/views/publicities/index.html.erb
<h1>Listing publicities</h1>

<table>
  <tr>
    <th>Titulo</th>
    <th>Contenido</th>
    <th>Fechainicio</th>
    <th>Fechafin</th>
    <th>Tarifa</th>
    <th>Nroclick</th>
    <th>Ubications</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @publicities.each do |publicity| %>
  <tr>
    <td><%= publicity.titulo %></td>
    <td><%= publicity.contenido %></td>
    <td><%= publicity.fechaInicio %></td>
    <td><%= publicity.fechaFin %></td>
    <td><%= publicity.tarifa %></td>
    <td><%= publicity.nroclick %></td>
    <td><%= publicity.ubications %></td>
    <td><%= link_to 'Show', publicity %></td>
    <td><%= link_to 'Edit', edit_publicity_path(publicity) %></td>
    <td><%= link_to 'Destroy', publicity, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Publicity', new_publicity_path %>

app/views/publicities/new.html.erb
<h1>New publicity</h1>

<%= render 'form' %>

<%= link_to 'Back', publicities_path %>

app/views/publicities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Titulo:</b>
  <%= @publicity.titulo %>
</p>

<p>
  <b>Contenido:</b>
  <%= image_tag @sportsfield.contenido.url %>
</p>

<p>
  <b>Fechainicio:</b>
  <%= @publicity.fechaInicio %>
</p>

<p>
  <b>Fechafin:</b>
  <%= @publicity.fechaFin %>
</p>

<p>
  <b>Tarifa:</b>
  <%= @publicity.tarifa %>
</p>

<p>
  <b>Nroclick:</b>
  <%= @publicity.nroclick %>
</p>

<p>
  <b>Ubications:</b>
  <%= @publicity.ubications %>
</p>


<%= link_to 'Edit', edit_publicity_path(@publicity) %> |
<%= link_to 'Back', publicities_path %>